name: NPM Publish

on:
  push: 
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      
      - name: Authenticate with Registry
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Configure Git user
        run: |
          git config --global user.email "ci@your-site.com"
          git config --global user.name "ci@$GITHUB_ACTOR"

      - name: Install dependencies
        run: yarn install

      - name: Publish package
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
